name: Build
on: 
  pull_request:

env:
  GO_VERSION: "1.22.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Install Dependencies
        run: |
          go mod download
      
      - name: Build Binary
        run: |
          VERSION=$(git describe --tags --always --dirty)
          COMMIT=$(git rev-parse --short HEAD)
          ARCH=$(go env GOHOSTARCH)
          SUFFIX="-${ARCH}"

          # Set linker flags
          LINKFLAGS="-X github.com/rancher/csp-adapter.Version=$VERSION"
          LINKFLAGS="-X github.com/rancher/csp-adapter.GitCommit=$COMMIT"

          CGO_ENABLED=0 go build -ldflags "$LINKFLAGS -extldflags -static -s" -o bin/csp-adapter
      
      - name: Run Tests
        run: |
          go test ./... -v
