name: Build
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Dapper CI
        run: dapper build
