name: Build
on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./setup.yml

      - name: Run Build
        run: make build

      - name: Run Tests
        run: make test
