name: Build
on: 
  pull_request:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run CI
        run: ./scripts/ci
      - name: Generate Checksum
        run: sha256sum $(find dist/artifacts -type f ! -name "*.tgz") > dist/artifacts/sha256sum-amd64.txt
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_dist_amd64
          path: dist/artifacts
      - name: Upload Binaries Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_bin_amd64
          path: bin

  build-arm64:
    runs-on: [self-hosted, Organization, org--rancher--arm64-containers]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up GO
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run CI
        run: ./scripts/ci
      - name: Generate Checksum
        run: sha256sum $(find dist/artifacts -type f ! -name "*.tgz") > dist/artifacts/sha256sum-arm64.txt
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_dist_arm64
          path: dist/artifacts
      - name: Upload Binaries Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github_bin_arm64
          path: bin

  merge-artifacts:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Merge Dist Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: github_dist
          pattern: github_dist*
          delete-merged: true
