name: Push Images
on: [workflow_call]
  
# Needed to access secrets and workflows
permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  multiarch-push:  
    runs-on: runs-on,runner=1cpu-linux-amd64,run-id=${{ github.run_id }}

    strategy:
      matrix:
        platform:
          - amd64
          - arm64

    # Needed to use gh cli
    env:
      GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Download Binaries Artifacts
      run: |
        ARTIFACT_NAME="github_bin_${{ matrix.platform }}"
        RUN_ID=$(gh run --repo ${{ github.repository }} list --workflow "build" --json databaseId,headSha -c ${{ github.sha }} --jq '.[].databaseId')
        gh run --repo ${{ github.repository }} download ${RUN_ID} -n ${ARTIFACT_NAME} -D bin
    - name: Read Secrets
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build Manifest
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: rancher/rancher-csp-adapter
        tags: |
          type=semver,enable=true,suffix=-${{ matrix.platform }},pattern={{version}}
        flavor: |
          latest=false
    - name: Build and Push to Docker Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        file: package/Dockerfile
        platforms: linux/${{ matrix.platform }}
