name: Push Images
on: [workflow_call]

jobs:
  docker-push-multiarch:  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Read Secrets
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
          secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr/credentials | ECR_ACCESS_KEY
          secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr/credentials | ECR_SECRET_KEY
          secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr-eu/credentials | ECR_ACCESS_KEY_EU
          secret/data/github/repo/${{ github.repository }}/aws/aws-rancher-csp-adapter-ecr-eu/credentials | ECR_SECRET_KEY_EU
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}  
    - name: Build and Push to Docker Registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: rancher/csp-adapter:${{ github.event.release.tag_name }}
        file: package/Dockerfile
        platforms: ${{ matrix.platform }}
