name: Release
on:
  push:
    tags: '*'
  pull_request:
    types:
      - closed
      
# Needed to create the release and access workflows
permissions:
  contents: write
  actions: read

jobs:
  github-release:
    # Run on merges and tag pushes
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    # Needed to create the release and use gh cli
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Download Distribution Artifacts
          run: |
            ARTIFACT_NAME="github_dist"
            RUN_ID=$(gh run --repo ${{ github.repository }} list --workflow "build" --json databaseId,headSha -c ${{ github.sha }} --jq '.[].databaseId')
            gh run --repo ${{ github.repository }} download ${RUN_ID} -n ${ARTIFACT_NAME} -D dist/artifacts
        - name: Checksum
          run: ./scripts/checksum
        - name: Create a Release
          uses: actions/create-release@v1
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref_name }}
            prerelease: true
        - name: Upload Assets
          run: |
            ASSETS_DIR="dist/artifacts"
            TAG=${{ github.ref_name }}
            for file in $ASSETS_DIR/*; do
              gh release upload $TAG $file --repo ${{ github.repository }}
            done

  push-images:
    needs: [github-release]
    uses: ./.github/workflows/publish-images.yml
    secrets: inherit
